openapi: 3.0.1
info:
  title: Coffee API
  version: '1.0'
  description: API to manage types of coffee.
  contact:
    name: Christian Behrenberg
    email: christian.behrenberg@gmail.com
  license:
    name: MIT
    url: 'https://github.com/cbehrenberg/oai3-springboot-coffee-api/blob/main/LICENSE'
servers:
  - url: 'http://localhost:8080'
    description: local
paths:
  /coffees:
    get:
      summary: List coffee types
      operationId: list-coffees
      description: Returns the current list of all coffee types.
      parameters:
        - schema:
            type: integer
            example: 10
            minimum: 1
            default: 10
          in: query
          name: limit
          description: Limit for pagination
        - schema:
            type: integer
            example: 5
            minimum: 0
          in: query
          name: offset
          description: 'Start for pagination, beginning with 0'
        - schema:
            type: string
          in: query
          name: sortBy
          description: 'Sort by JSON path, otherwise by id'
        - schema:
            type: string
          in: query
          name: filter
          description: Filter expression
        - schema:
            type: string
            enum:
              - asc
              - desc
            example: desc
            default: asc
          in: query
          name: orderBy
          description: Asc(ending) or desc(ending) on sortBy field
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  coffees:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          minLength: 1
                          description: Id of the coffee type
                          example: 6b4c3f58
                        coffee:
                          $ref: '#/components/schemas/CoffeeType'
                      required:
                        - id
                        - coffee
                required:
                  - coffees
              examples: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
        - coffee
    post:
      summary: Create coffee type
      operationId: create-coffee
      description: Creates a new type of coffee and assigns an id.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeType'
            examples: {}
        description: Type of coffee that is to be newly created.
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                    description: Id of the created coffee type
                    example: afad07ce
                required:
                  - id
              examples: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
        - coffee
  '/coffees/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get coffee type
      tags:
        - coffee
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoffeeType'
              examples: {}
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/InternalServerError'
      operationId: get-coffee-id
      description: Returns the current coffee type information.
    put:
      summary: Update coffee type
      operationId: update-coffee-id
      responses:
        '200':
          description: OK
        '201':
          description: Created
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                    description: Id of the created coffee type
                    example: afad07ce
                required:
                  - id
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/InternalServerError'
      description: 'Replaces coffee type data, or creates a new such resource. Fails, if the id has already been assigned.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeType'
            examples: {}
        description: 'Coffee type data to be overwritten, or to be created.'
      tags:
        - coffee
    delete:
      summary: Delete coffee type
      operationId: delete-coffee-id
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/InternalServerError'
      description: Deletes a type of coffee.
      tags:
        - coffee
    patch:
      summary: Partially update coffee type
      operationId: patch-coffee-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoffeeType'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/InternalServerError'
      description: Partially overwrites the data of a coffee type.
      tags:
        - coffee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonPatch'
        description: JSON patch description for changing the type of coffee
  '/coffees/{id}/image':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get coffee type image
      tags:
        - coffee
      responses:
        '200':
          description: OK
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
                description: Raw binary data of the image file
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/InternalServerError'
      operationId: get-coffee-id-image
      description: Returns the image of a coffee type
    put:
      summary: Upload coffee type image
      operationId: put-coffee-id-image
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Not Found
        '406':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      description: Uploads a coffee type image or replaces the existing one
      requestBody:
        content:
          image/jpeg:
            schema:
              type: string
              format: binary
              description: Raw binary data of the image file
        description: Binary file of the image to be uploaded
      tags:
        - coffee
    delete:
      summary: Delete coffee type image
      operationId: delete-coffee-id-image
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/InternalServerError'
      description: Deletes an existing coffee type image
      tags:
        - coffee
components:
  schemas:
    CoffeeType:
      description: 'Describes a type of coffee in terms of name, manufacturer, price, taste and composition.'
      type: object
      title: Coffee Type
      properties:
        roastery:
          type: string
          minLength: 1
          example: Lavazza
          description: Maker of the coffee
        name:
          type: string
          minLength: 1
          description: Name of the type of coffee
          example: Caffè Crema Classico
        priceEurKg:
          type: number
          description: Price per kilogram in euros
          minimum: 0
          example: 10.79
          multipleOf: 0.01
          format: float
        blend:
          type: object
          description: Describes the blend based on the percentage of certain types of coffee beans
          minProperties: 1
          properties:
            arabica:
              type: number
              description: Proportion of the Arabica bean in the blend
              format: float
              example: 0.7
              minimum: 0
              maximum: 1
              multipleOf: 0.01
            robusta:
              type: number
              description: Proportion of Robusta bean in the blend
              example: 0.3
              format: float
              minimum: 0
              maximum: 1
              multipleOf: 0.01
        taste:
          type: object
          description: Describes the taste of the coffee type based on the weighting of certain criteria.
          minProperties: 1
          properties:
            strength:
              type: number
              description: Strength of the coffee on the tongue
              minimum: 0
              maximum: 1
              multipleOf: 0.01
              example: 0.9
              format: float
            caffeine:
              type: number
              description: 'Caffeine degree of the coffee type - if the value is 0, then this is a decaffeinated coffee'
              format: float
              example: 0.8
              minimum: 0
              maximum: 1
              multipleOf: 0.01
            roastLevel:
              type: number
              description: Degree of roast of the coffee beans used
              example: 0.7
              format: float
              minimum: 0
              maximum: 1
              multipleOf: 0.01
            crema:
              type: number
              description: Character and beauty of the coffee crema
              format: float
              example: 0.9
              minimum: 0
              maximum: 1
              multipleOf: 0.01
      required:
        - roastery
        - name
    JsonPatch:
      type: array
      description: 'Simple JSON patch model for generic PATCH operations, see http://jsonpatch.com/'
      minItems: 1
      uniqueItems: true
      title: JSON Patch
      items:
        type: object
        properties:
          op:
            type: string
            minLength: 1
            enum:
              - add
              - remove
              - replace
            example: replace
            description: Patch operation
          path:
            type: string
            minLength: 1
            description: JSON pointer in the document to be patched
          value:
            type: string
            minLength: 1
        required:
          - op
          - path
          - value
    Error:
      description: Error description
      type: object
      properties:
        code:
          type: string
          minLength: 1
          description: One of a server-defined set of error codes
        message:
          type: string
          minLength: 1
          example: Previous passwords may not be reused
      required:
        - code
        - message
  responses:
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            description: Internal Server Error details
            type: object
            properties:
              error:
                $ref: '#/components/schemas/Error'
            required:
              - error
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            description: Bad Request details
            type: object
            properties:
              error:
                $ref: '#/components/schemas/Error'
            required:
              - error
tags:
  - name: coffee
