openapi: 3.1.0
info:
  title: Coffee API
  version: '1.0'
  description: API to manage types of coffee.
  summary: API to manage types of coffee
  contact:
    name: Christian Behrenberg
    email: christian.behrenberg@gmail.com
  license:
    name: MIT
    url: 'https://github.com/cbehrenberg/oai3-springboot-coffee-api/blob/main/LICENSE'
servers:
  - url: 'http://localhost:8080/v1'
    description: localhost
paths:
  /coffees:
    get:
      summary: List coffee types
      operationId: list-coffees
      description: Returns the current list of all coffee types.
      parameters:
        - schema:
            type: integer
            example: 10
            minimum: 1
            default: 10
          in: query
          name: top
          description: Limit for pagination
        - schema:
            type: integer
            example: 5
            minimum: 0
          in: query
          name: skip
          description: 'Start for pagination, beginning with 0'
        - schema:
            type: string
            example: name desc
          in: query
          name: orderBy
          description: 'Order by JSON path, asc(ending, default) or desc(ending)'
        - schema:
            type: string
            example: roastery eq 'Lavazza'
          in: query
          name: filter
          description: Filter expression
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  coffees:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          minLength: 1
                          description: Id of the coffee type
                          example: 6b4c3f58
                        coffee:
                          $ref: '#/components/schemas/CoffeeType'
                      required:
                        - id
                        - coffee
                  next:
                    type: string
                    description: Next link for pagination
                required:
                  - coffees
              examples: {}
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - coffee
    post:
      summary: Create coffee
      operationId: create-coffee
      description: Creates a new type of coffee and assigns an id.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeType'
            examples: {}
        description: Type of coffee that is to be newly created.
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                    description: Id of the created coffee type
                    example: afad07ce
                required:
                  - id
              examples: {}
        '400':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      tags:
        - coffee
  '/coffees/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get coffee type
      tags:
        - coffee
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CoffeeType'
              examples: {}
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/Error'
      operationId: get-coffee-id
      description: Return the current coffee type information.
    put:
      summary: Update coffee
      operationId: update-coffee-id
      responses:
        '200':
          description: OK
        '201':
          description: Created
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                    description: Id of the created coffee type
                    example: afad07ce
                required:
                  - id
        '400':
          $ref: '#/components/responses/Error'
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/Error'
      description: 'Replaces coffee type data, or creates a new such resource. Fails, if the id has already been assigned.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeType'
            examples: {}
        description: 'Coffee type data to be overwritten, or to be created.'
      tags:
        - coffee
    delete:
      summary: Delete coffee
      operationId: delete-coffee-id
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/Error'
      description: Deletes a type of coffee.
      tags:
        - coffee
    patch:
      summary: ''
      operationId: patch-coffee-id
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/Error'
        '404':
          description: Not Found
        '500':
          $ref: '#/components/responses/Error'
      description: Partially overwrites the data of a coffee type.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoffeeType'
      tags:
        - coffee
components:
  schemas:
    CoffeeType:
      description: 'Describes a type of coffee in terms of name, manufacturer, price, taste and composition.'
      type: object
      examples:
        - roastery: Lucaffe
          name: Blucaffé
          priceEurKg: 44.14
          blend:
            arabica: 0.9
            robusta: 0.1
          taste:
            strength: 0.3
            caffeine: 0.7
            roastLevel: 0.7
            crema: 0.7
        - roastery: Kimbo
          name: Decaffeinated
          priceEurKg: 20.41
          blend:
            arabica: 0.7
            robusta: 0.3
          taste:
            strength: 0.7
            caffeine: 0
            roastLevel: 0.7
            crema: 0.7
      title: Coffee Type
      properties:
        roastery:
          type: string
          minLength: 1
          example: Lavaza
          description: Maker of the coffee
        name:
          type: string
          minLength: 1
          description: Name of the type of coffee
          example: Caffè Crema Classico
        priceEurKg:
          type: number
          description: Price per kilogram in euros
          minimum: 0
          example: 10.79
          multipleOf: 0.01
          format: float
        blend:
          type: object
          description: Describes the blend based on the percentage of certain types of coffee beans
          minProperties: 1
          properties:
            arabica:
              type: number
              description: Proportion of the Arabica bean in the blend
              format: float
              example: 0.7
              minimum: 0
              maximum: 1
              multipleOf: 0.01
            robusta:
              type: number
              description: Proportion of Robusta bean in the blend
              example: 0.3
              format: float
              minimum: 0
              maximum: 1
              multipleOf: 0.01
        taste:
          type: object
          description: Describes the taste of the coffee type based on the weighting of certain criteria.
          minProperties: 1
          properties:
            strength:
              type: number
              description: Strength of the coffee on the tongue
              minimum: 0
              maximum: 1
              multipleOf: 0.01
              example: 0.9
              format: float
            caffeine:
              type: number
              description: 'Caffeine degree of the coffee type - if the value is 0, then this is a decaffeinated coffee'
              format: float
              example: 0.8
              minimum: 0
              maximum: 1
              multipleOf: 0.01
            roastLevel:
              type: number
              description: Degree of roast of the coffee beans used
              example: 0.7
              format: float
              minimum: 0
              maximum: 1
              multipleOf: 0.01
            crema:
              type: number
              description: Character and beauty of the coffee crema
              format: float
              example: 0.9
              minimum: 0
              maximum: 1
              multipleOf: 0.01
      required:
        - roastery
        - name
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              error:
                type: object
                required:
                  - code
                  - message
                properties:
                  code:
                    type: string
                    minLength: 1
                    description: One of a server-defined set of error codes
                    example: BadArgument
                  message:
                    type: string
                    minLength: 1
                    description: A human-readable representation of the error
                    example: Previous passwords may not be reused
            required:
              - error
tags:
  - name: coffee
